USE HESS;

DROP TABLE IF EXISTS BatteryStatus;
DROP TABLE IF EXISTS PeakSchedule;
DROP TABLE IF EXISTS PeakType;
DROP TABLE IF EXISTS WeekType;

DROP TABLE IF EXISTS PowerUsageData;
DROP TABLE IF EXISTS PowerCost;
DROP TABLE IF EXISTS ScriptState;

DROP DATABASE IF EXISTS HESS;
