USE HESS;


USE a4060350_HESS;
DROP TABLE IF EXISTS BatteryStatus;
DROP TABLE IF EXISTS PeakSchedule;
DROP TABLE IF EXISTS PeakType;
DROP TABLE IF EXISTS WeekType;



DROP TABLE IF EXISTS UsageData;
DROP TABLE IF EXISTS PowerCost;
DROP DATABASE IF EXISTS HESS;




